# ================================================================
# SHARED CONFIGURATION (TẤT CẢ CÁC SERVICE ĐỀU LOAD)
# ================================================================

# Cấu hình log mức độ INFO, cảnh báo từ Spring framework ở mức WARN
logging.level.root=INFO
logging.level.org.springframework=WARN

# Mở các endpoint giám sát của Spring Boot Actuator
management.endpoints.web.exposure.include=health,info,refresh,busrefresh
management.endpoint.health.show-details=always
