# ================================================================
# SHARED CONFIGURATION - DEV PROFILE (CHẠY LOCAL)
# ================================================================

# Địa chỉ Eureka Server chạy ở máy local của Developer
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
