# Database PostgreSQL cho Order Service chạy local qua Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/orderdb?options=-c%20timezone=GMT%2B7
spring.datasource.username=order_svc
spring.datasource.password=order_secret_123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
